// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKbr6onbjHieB2wPDqMhtIdn4V61NpDOQ',
    appId: '1:1068369092202:web:3509bccf5953e4f5193413',
    messagingSenderId: '1068369092202',
    projectId: 'password-saver-b61a6',
    authDomain: 'password-saver-b61a6.firebaseapp.com',
    storageBucket: 'password-saver-b61a6.appspot.com',
    measurementId: 'G-QP364V01RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJ1f2_PIXEKzq35YK7YGDvtOcRIdzDtk',
    appId: '1:1068369092202:android:a71376e1332b1129193413',
    messagingSenderId: '1068369092202',
    projectId: 'password-saver-b61a6',
    storageBucket: 'password-saver-b61a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEkOzcWXrjkz2nKp-R9V-KIlkdFmpVK8I',
    appId: '1:1068369092202:ios:963d5d93dc6c215d193413',
    messagingSenderId: '1068369092202',
    projectId: 'password-saver-b61a6',
    storageBucket: 'password-saver-b61a6.appspot.com',
    iosBundleId: 'com.example.passwordSaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEkOzcWXrjkz2nKp-R9V-KIlkdFmpVK8I',
    appId: '1:1068369092202:ios:963d5d93dc6c215d193413',
    messagingSenderId: '1068369092202',
    projectId: 'password-saver-b61a6',
    storageBucket: 'password-saver-b61a6.appspot.com',
    iosBundleId: 'com.example.passwordSaver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKbr6onbjHieB2wPDqMhtIdn4V61NpDOQ',
    appId: '1:1068369092202:web:cdf8a6b983da12db193413',
    messagingSenderId: '1068369092202',
    projectId: 'password-saver-b61a6',
    authDomain: 'password-saver-b61a6.firebaseapp.com',
    storageBucket: 'password-saver-b61a6.appspot.com',
    measurementId: 'G-Z0LTTEEH8L',
  );
}
